# Generated by Django 5.0.6 on 2024-07-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimerecord',
            name='clicked_responded_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
