# Generated by Django 5.0.6 on 2024-07-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datetimerecord_clicked_responded_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimerecord',
            name='clicked_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
