# Generated by Django 5.0.6 on 2024-07-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_datetimerecord_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetimerecord',
            old_name='clicked_datetime',
            new_name='failed_click_datetime',
        ),
        migrations.RenameField(
            model_name='datetimerecord',
            old_name='clicked_responded_datetime',
            new_name='failed_responded_datetime',
        ),
        migrations.RenameField(
            model_name='datetimerecord',
            old_name='record_id',
            new_name='id',
        ),
    ]
